name : my first github project
on: push
jobs:
  my_first_job:
    runs-on: ubuntu-latest
    steps:
      - name: my first print
        run: echo " my first action job"
      
      - name: list files
        run: ls


      - name: read files
        run: |
          echo " hey messgae" > main.txt
          cat main.txt
        

    
   